/**
 * Tiny logistic-regression learner (batch gradient descent with L2) used for
 * the "TSR escalation predictor": the probability that a pending defect will
 * force a (new or stricter) temporary speed restriction within 30 days if it
 * is not attended.
 *
 * Training data comes from the historical defect register generated by the
 * data factory (which encodes realistic but synthetic relationships between
 * condition metrics and escalation). Features are standardised inside the
 * model so callers pass raw values.
 */

export const ESCALATION_FEATURES = [
  { key: 'daysOverdue', label: 'Days overdue' },
  { key: 'conditionIndex', label: 'Condition index (0 good – 1 bad)' },
  { key: 'gmtLoad', label: 'Traffic load (GMT / yr)' },
  { key: 'ageRatio', label: 'Age ÷ characteristic life' },
  { key: 'safety', label: 'Safety severity of work type' },
  { key: 'hasTsr', label: 'TSR already imposed' }
];

function sigmoid(z) {
  return 1 / (1 + Math.exp(-z));
}

export class LogisticModel {
  constructor(featureKeys = ESCALATION_FEATURES.map((f) => f.key)) {
    this.keys = featureKeys;
    this.mean = featureKeys.map(() => 0);
    this.sd = featureKeys.map(() => 1);
    this.w = featureKeys.map(() => 0);
    this.b = 0;
    this.trained = false;
    this.metrics = null;
  }

  vector(sample) {
    return this.keys.map((k, i) => ((Number(sample[k]) || 0) - this.mean[i]) / this.sd[i]);
  }

  fit(samples, { epochs = 400, lr = 0.15, l2 = 0.002 } = {}) {
    const n = samples.length;
    if (n === 0) return this;
    // standardise
    this.keys.forEach((k, i) => {
      const vals = samples.map((s) => Number(s[k]) || 0);
      const mean = vals.reduce((a, b) => a + b, 0) / n;
      const sd = Math.sqrt(vals.reduce((a, b) => a + (b - mean) ** 2, 0) / n) || 1;
      this.mean[i] = mean;
      this.sd[i] = sd;
    });
    const X = samples.map((s) => this.vector(s));
    const y = samples.map((s) => (s.escalated ? 1 : 0));
    for (let e = 0; e < epochs; e++) {
      const grad = this.w.map(() => 0);
      let gb = 0;
      for (let i = 0; i < n; i++) {
        const p = sigmoid(X[i].reduce((s, x, j) => s + x * this.w[j], this.b));
        const err = p - y[i];
        for (let j = 0; j < this.w.length; j++) grad[j] += err * X[i][j];
        gb += err;
      }
      for (let j = 0; j < this.w.length; j++) this.w[j] -= lr * (grad[j] / n + l2 * this.w[j]);
      this.b -= lr * (gb / n);
    }
    this.trained = true;
    return this;
  }

  predict(sample) {
    const x = this.vector(sample);
    return sigmoid(x.reduce((s, v, j) => s + v * this.w[j], this.b));
  }

  /** Per-feature contribution (standardised value × weight) for explanations. */
  contributions(sample) {
    const x = this.vector(sample);
    return this.keys.map((k, j) => ({ key: k, value: sample[k], contribution: x[j] * this.w[j] }));
  }

  evaluate(samples) {
    let tp = 0;
    let fp = 0;
    let tn = 0;
    let fn = 0;
    let logLoss = 0;
    const scored = samples.map((s) => ({ p: this.predict(s), y: s.escalated ? 1 : 0 }));
    for (const { p, y } of scored) {
      const pc = Math.min(Math.max(p, 1e-9), 1 - 1e-9);
      logLoss += -(y * Math.log(pc) + (1 - y) * Math.log(1 - pc));
      const pred = p >= 0.5 ? 1 : 0;
      if (pred === 1 && y === 1) tp++;
      else if (pred === 1 && y === 0) fp++;
      else if (pred === 0 && y === 0) tn++;
      else fn++;
    }
    // AUC by rank statistic
    const pos = scored.filter((s) => s.y === 1).map((s) => s.p);
    const neg = scored.filter((s) => s.y === 0).map((s) => s.p);
    let wins = 0;
    for (const a of pos) for (const b of neg) wins += a > b ? 1 : a === b ? 0.5 : 0;
    const auc = pos.length && neg.length ? wins / (pos.length * neg.length) : NaN;
    const n = samples.length || 1;
    this.metrics = {
      n: samples.length,
      accuracy: (tp + tn) / n,
      precision: tp / (tp + fp || 1),
      recall: tp / (tp + fn || 1),
      auc,
      logLoss: logLoss / n,
      confusion: { tp, fp, tn, fn }
    };
    return this.metrics;
  }
}
