/**
 * FormsPage — the forms the plan implies (docs/v4-spec.md §3.8).
 *  - control: TSR register, caution orders T/409 and T/409B, T/351 register
 *  - tms: TSRs on the corridor (propose, request relaxation), T/409 preview
 *  - smms: T/351 register (issue, mark reconnected)
 *  - tdms: power-block isolation record (de-energised / energised)
 * Orders and notices are generated by the engine from the working blocks and
 * the TSR register; statuses are recorded with store actions. Every printed
 * form goes through FormSheet (not-official watermark).
 */
import { useMemo, useState, type CSSProperties, type ReactNode } from 'react';
import { FileText, PlusCircle, ShieldAlert, Wrench, Zap } from 'lucide-react';
import { usePortal } from '../../app/usePortal';
import { can, type PortalId } from '../../auth/portals';
import { WORK_TYPES } from '../../engine/constants.js';
import { cautionOrders, disconnectionNoticesWeek, workingBlocks, type CautionOrder, type DisconnectionNotice, type WorkingBlock } from '../../engine/select';
import type { Dept, Line, Snapshot } from '../../engine/types';
import { useT } from '../../i18n';
import { clamp, dateLabel, dateLong, hhmm, kmRange, lineLabel, num, timeAgo } from '../../lib/format';
import { useAppStore, type ManualTsr } from '../../store/useAppStore';
import { Badge, Card, CardBody, CardHead, DataTable, EmptyState, Field, Modal, PageHeader, PlanPending, StatTile, StatusBadge, Tabs, type Column } from '../../components/ui';
import { FormSheet, PrintButton, SimLabel } from '../../components/ui/extras';
import { BlockDrawer } from '../../components/domain/BlockDrawer';
import { TaskDrawer } from '../../components/domain/TaskDrawer';
import { useDrawerParams } from '../../components/domain/useDrawerParams';

export interface FormsPageProps {
  tab?: 'caution' | 'disconnections' | 'powerblocks';
}

type TabId = 'tsr' | 'caution' | 'cautionB' | 't351' | 'power';
type Role = 'control' | 'tms' | 'smms' | 'tdms';
const TABS: Record<Role, TabId[]> = { control: ['caution', 'cautionB', 'tsr', 't351'], tms: ['caution', 'tsr'], smms: ['t351'], tdms: ['power'] };

interface WorkTypeDef {
  dept: Dept;
  label: string;
}
const WT = WORK_TYPES as Record<string, WorkTypeDef>;

const strings = {
  en: {
    title: 'Caution orders & forms',
    ledeControl: 'TSR register, caution orders (T/409, T/409B) and the T/351 register, generated from the working plan. Issue, withdraw and print.',
    ledeTms: 'TSRs on the corridor and the caution orders they produce. Propose a TSR after your work or request a relaxation.',
    ledeSmms: 'T/351 disconnection notices for every S&T work in a block. Issue the notice and record reconnection.',
    ledeTdms: 'Power-block isolation record for every block that needs OHE power off. Print the isolation sheet.',
    nomenclature: 'Form nomenclature follows the engine (T/409, T/409B, T/351).',
    tpcNote: 'TPC interaction recorded in-app; no SCADA link.',
    planDay: 'Plan day',
    tabTsr: 'TSR register',
    tabCaution: 'Caution orders T/409',
    tabCautionB: 'T/409B',
    tabT351: 'T/351 register',
    tabPower: 'Power blocks',
    statTsr: 'TSRs in force',
    statTsrSub: '{p} proposed · {r} relaxation requested',
    statOrders: 'Caution orders · {date}',
    statOrdersSub: '{issued} issued · {draft} draft',
    statT351: 'T/351 this week',
    statT351Sub: '{open} not yet received',
    statPower: 'Power blocks this week',
    statPowerSub: '{n} de-energised',
    addTsr: 'Add TSR',
    proposeTsr: 'Propose TSR',
    noCaution: 'Issuing and imposing needs the issue-caution capability.',
    noIntake: 'Proposing needs the intake capability.',
    station: 'Station',
    allStations: 'All stations',
    colNo: 'No.',
    colSection: 'Section',
    colSpeed: 'Speed',
    colValid: 'Valid',
    colReason: 'Reason',
    colStatus: 'Status',
    colSince: 'Since',
    colLoss: 'Train-min/day',
    colBlock: 'Block',
    colGear: 'Gear / work',
    colTime: 'Disconnect → reconnect',
    colOhe: 'Elementary sections',
    colActions: '',
    untilCancelled: 'Until cancelled',
    normalSpeed: 'normal {v} km/h',
    relaxRequested: 'Relaxation requested',
    impose: 'Impose',
    withdraw: 'Withdraw',
    relax: 'Request relaxation',
    issue: 'Issue',
    markReceived: 'Mark received',
    markReconnected: 'Mark reconnected',
    deenergise: 'Mark de-energised',
    energise: 'Mark energised',
    openBlock: 'Block',
    withdrawNeeds: 'Withdraw needs a relaxation request from TMS or a line-clear record for its block.',
    issueProposed: 'Impose the TSR in the register first.',
    noDeptCap: 'This action needs the execute or intake capability of the department.',
    powerPending: 'Pending',
    powerDeenergised: 'De-energised',
    powerEnergised: 'Energised',
    recordedBy: '{by} · {when}',
    previewTitle: 'Print preview',
    previewEmpty: 'Select a row to preview its form.',
    print: 'Print form',
    emptyTsr: 'No manual TSRs on this corridor.',
    emptyCaution: 'No T/409 caution orders on {date}. Orders appear for register TSRs and manual TSRs in force.',
    emptyCautionB: 'No T/409B orders on {date}. They appear on the day of a block with tamping or deep screening.',
    emptyT351: 'No T/351 notices this week. Notices appear for blocks with S&T work.',
    emptyPower: 'No power blocks this week. Isolation sheets appear for blocks that need OHE power off.',
    sheetDivision: 'Division',
    sheetDate: 'Date',
    sheetTo: 'To',
    sheetToCaution: 'Loco pilots and guards of all trains; station masters of the section',
    sheetToNotice: 'Station master on duty, {section}',
    sheetBetween: 'Between',
    sheetLine: 'Line',
    sheetCautionSpeed: 'Caution speed',
    sheetNormal: 'Normal speed',
    sheetReason: 'Reason',
    sheetValid: 'Valid',
    sheetTrains: 'Trains through the block window',
    sheetIssuedBy: 'Issued by',
    sheetStatus: 'Status',
    sheetSm: 'Station Master',
    sheetSc: 'Section Controller',
    sheetBlock: 'Block',
    sheetWindow: 'Window',
    sheetGear: 'Gear to be disconnected',
    sheetDisconnect: 'Disconnection',
    sheetReconnect: 'Reconnection',
    sheetSafety: 'Safety assurance',
    sheetIncharge: 'In-charge',
    sheetSse: 'SSE / JE (Signal)',
    sheetIsolation: 'Elementary sections to be isolated',
    sheetSp: 'From SP → to SP',
    sheetTpc: 'TPC record',
    sheetTower: 'Tower wagon',
    sheetTrd: 'SSE / TRD',
    sheetTpcSign: 'Traction Power Controller',
    sheetPowerTitle: 'Power block isolation sheet',
    fs_DRAFT: 'Draft',
    fs_ISSUED: 'Issued',
    fs_RECEIVED: 'Received',
    fs_RECONNECTED: 'Reconnected',
    fs_WITHDRAWN: 'Withdrawn',
    fs_ACKNOWLEDGED: 'Acknowledged',
    none: '—',
    tsrTitleAdd: 'Add TSR (in force)',
    tsrTitlePropose: 'Propose TSR',
    tsrBodyAdd: 'The TSR is in force at once; its T/409 is generated for every train through the stretch.',
    tsrBodyPropose: 'The proposal goes to Control, who imposes it.',
    fLine: 'Line',
    fFrom: 'From km',
    fTo: 'To km',
    fSpeed: 'Speed (km/h)',
    fReason: 'Reason',
    fInject: 'Also inject the attending work into the plan (re-plans the week)',
    fWork: 'Attending work',
    fWorkPick: 'Choose the work',
    errKm: 'Km range must lie within the corridor (0–{len} km), from ≤ to.',
    errSpeed: 'Speed must be below the sectional speed of {mps} km/h.',
    errReason: 'A reason is required.',
    errWork: 'Choose the attending work.',
    confirm: 'Confirm',
    cancel: 'Cancel',
    lineUp: 'UP line',
    lineDn: 'DN line',
    lineBoth: 'Both lines',
    relaxTitle: 'Request relaxation · {id}',
    relaxBody: 'Control is told that the stretch can take a higher speed.',
    relaxSpeed: 'Proposed speed (km/h)',
    relaxNote: 'Basis (tamping runs, consolidation, measurement)',
    errRelax: 'Proposed speed must be above {v} and below {mps} km/h.',
    relaxNoteText: 'Relax to {v} km/h: {note}',
    withdrawTsrTitle: 'Withdraw TSR · {id}',
    withdrawOrderTitle: 'Withdraw order · {id}',
    withdrawReason: 'Reason for withdrawal',
    toastTsrInForce: 'TSR {a}–{b} at {v} km/h in force',
    toastTsrProposed: 'TSR {a}–{b} at {v} km/h proposed to Control',
    toastInjected: 'Attending work injected; the plan is being recomputed',
    toastImposed: 'TSR {id} in force',
    toastWithdrawn: 'TSR {id} withdrawn',
    toastRelax: 'Relaxation requested on {id}',
    toastIssued: 'Issued {form} {serial}',
    toastOrderWithdrawn: 'Order {serial} withdrawn',
    toastReceived: 'T/351 {serial} marked received',
    toastReconnected: 'T/351 {serial} marked reconnected',
    toastPower: '{id}: {state}',
    notifyRelax: 'Relaxation requested on {id}',
    notifyImposed: 'TSR {id} in force',
    notifyWithdrawn: 'TSR {id} withdrawn',
    replanReason: 'emergency TSR {id}',
  },
  hi: {
    title: 'सावधानी आदेश व प्रपत्र',
    ledeControl: 'कार्यकारी योजना से बने TSR रजिस्टर, सावधानी आदेश (T/409, T/409B) और T/351 रजिस्टर। जारी करें, वापस लें और प्रिंट करें।',
    ledeTms: 'कॉरिडोर के TSR और उनसे बने सावधानी आदेश। कार्य के बाद TSR प्रस्तावित करें या शिथिलन का अनुरोध करें।',
    ledeSmms: 'block में हर S&T कार्य के लिए T/351 डिस्कनेक्शन नोटिस। नोटिस जारी करें और रीकनेक्शन दर्ज करें।',
    ledeTdms: 'OHE बिजली बंद करने वाले हर block का पावर-block आइसोलेशन रिकॉर्ड। आइसोलेशन शीट प्रिंट करें।',
    nomenclature: 'प्रपत्रों के नाम इंजन के अनुसार (T/409, T/409B, T/351)।',
    tpcNote: 'TPC संवाद ऐप में दर्ज; कोई SCADA लिंक नहीं।',
    planDay: 'योजना दिवस',
    tabTsr: 'TSR रजिस्टर',
    tabCaution: 'सावधानी आदेश T/409',
    tabCautionB: 'T/409B',
    tabT351: 'T/351 रजिस्टर',
    tabPower: 'पावर block',
    statTsr: 'लागू TSR',
    statTsrSub: '{p} प्रस्तावित · {r} शिथिलन अनुरोध',
    statOrders: 'सावधानी आदेश · {date}',
    statOrdersSub: '{issued} जारी · {draft} प्रारूप',
    statT351: 'इस सप्ताह T/351',
    statT351Sub: '{open} अभी प्राप्त नहीं',
    statPower: 'इस सप्ताह पावर block',
    statPowerSub: '{n} डी-एनर्जाइज़्ड',
    addTsr: 'TSR जोड़ें',
    proposeTsr: 'TSR प्रस्तावित करें',
    noCaution: 'जारी करने और लागू करने के लिए issue-caution अधिकार चाहिए।',
    noIntake: 'प्रस्ताव के लिए intake अधिकार चाहिए।',
    station: 'स्टेशन',
    allStations: 'सभी स्टेशन',
    colNo: 'सं.',
    colSection: 'सेक्शन',
    colSpeed: 'गति',
    colValid: 'वैधता',
    colReason: 'कारण',
    colStatus: 'स्थिति',
    colSince: 'कब से',
    colLoss: 'ट्रेन-मिनट/दिन',
    colBlock: 'Block',
    colGear: 'गियर / कार्य',
    colTime: 'डिस्कनेक्ट → रीकनेक्ट',
    colOhe: 'एलीमेंट्री सेक्शन',
    colActions: '',
    untilCancelled: 'रद्द होने तक',
    normalSpeed: 'सामान्य {v} किमी/घं',
    relaxRequested: 'शिथिलन अनुरोधित',
    impose: 'लागू करें',
    withdraw: 'वापस लें',
    relax: 'शिथिलन अनुरोध',
    issue: 'जारी करें',
    markReceived: 'प्राप्त दर्ज करें',
    markReconnected: 'रीकनेक्ट दर्ज करें',
    deenergise: 'डी-एनर्जाइज़ दर्ज करें',
    energise: 'एनर्जाइज़ दर्ज करें',
    openBlock: 'Block',
    withdrawNeeds: 'वापस लेने के लिए TMS का शिथिलन अनुरोध या उसके block का लाइन-क्लियर रिकॉर्ड चाहिए।',
    issueProposed: 'पहले रजिस्टर में TSR लागू करें।',
    noDeptCap: 'इस कार्य के लिए विभाग का execute या intake अधिकार चाहिए।',
    powerPending: 'लंबित',
    powerDeenergised: 'डी-एनर्जाइज़्ड',
    powerEnergised: 'एनर्जाइज़्ड',
    recordedBy: '{by} · {when}',
    previewTitle: 'प्रिंट पूर्वावलोकन',
    previewEmpty: 'प्रपत्र देखने के लिए पंक्ति चुनें।',
    print: 'प्रपत्र प्रिंट करें',
    emptyTsr: 'इस कॉरिडोर पर कोई मैनुअल TSR नहीं।',
    emptyCaution: '{date} को कोई T/409 सावधानी आदेश नहीं। आदेश रजिस्टर TSR और लागू मैनुअल TSR के लिए बनते हैं।',
    emptyCautionB: '{date} को कोई T/409B आदेश नहीं। ये टैम्पिंग या डीप स्क्रीनिंग वाले block के दिन बनते हैं।',
    emptyT351: 'इस सप्ताह कोई T/351 नोटिस नहीं। नोटिस S&T कार्य वाले block के लिए बनते हैं।',
    emptyPower: 'इस सप्ताह कोई पावर block नहीं। आइसोलेशन शीट OHE बिजली बंद करने वाले block के लिए बनती हैं।',
    sheetDivision: 'मंडल',
    sheetDate: 'दिनांक',
    sheetTo: 'प्रति',
    sheetToCaution: 'सभी ट्रेनों के लोको पायलट और गार्ड; सेक्शन के स्टेशन मास्टर',
    sheetToNotice: 'ड्यूटी पर स्टेशन मास्टर, {section}',
    sheetBetween: 'के बीच',
    sheetLine: 'लाइन',
    sheetCautionSpeed: 'सावधानी गति',
    sheetNormal: 'सामान्य गति',
    sheetReason: 'कारण',
    sheetValid: 'वैधता',
    sheetTrains: 'block विंडो से गुजरने वाली ट्रेनें',
    sheetIssuedBy: 'जारीकर्ता',
    sheetStatus: 'स्थिति',
    sheetSm: 'स्टेशन मास्टर',
    sheetSc: 'सेक्शन नियंत्रक',
    sheetBlock: 'Block',
    sheetWindow: 'विंडो',
    sheetGear: 'डिस्कनेक्ट होने वाला गियर',
    sheetDisconnect: 'डिस्कनेक्शन',
    sheetReconnect: 'रीकनेक्शन',
    sheetSafety: 'संरक्षा आश्वासन',
    sheetIncharge: 'प्रभारी',
    sheetSse: 'SSE / JE (सिग्नल)',
    sheetIsolation: 'आइसोलेट होने वाले एलीमेंट्री सेक्शन',
    sheetSp: 'SP से → SP तक',
    sheetTpc: 'TPC रिकॉर्ड',
    sheetTower: 'टावर वैगन',
    sheetTrd: 'SSE / TRD',
    sheetTpcSign: 'कर्षण पावर नियंत्रक',
    sheetPowerTitle: 'पावर block आइसोलेशन शीट',
    fs_DRAFT: 'प्रारूप',
    fs_ISSUED: 'जारी',
    fs_RECEIVED: 'प्राप्त',
    fs_RECONNECTED: 'रीकनेक्ट',
    fs_WITHDRAWN: 'वापस लिया',
    fs_ACKNOWLEDGED: 'पावती दी',
    none: '—',
    tsrTitleAdd: 'TSR जोड़ें (लागू)',
    tsrTitlePropose: 'TSR प्रस्तावित करें',
    tsrBodyAdd: 'TSR तुरंत लागू होता है; उस हिस्से से गुजरने वाली हर ट्रेन के लिए T/409 बनता है।',
    tsrBodyPropose: 'प्रस्ताव नियंत्रण को जाता है, जो इसे लागू करता है।',
    fLine: 'लाइन',
    fFrom: 'किमी से',
    fTo: 'किमी तक',
    fSpeed: 'गति (किमी/घं)',
    fReason: 'कारण',
    fInject: 'संबंधित कार्य भी योजना में जोड़ें (सप्ताह की पुनः योजना होगी)',
    fWork: 'संबंधित कार्य',
    fWorkPick: 'कार्य चुनें',
    errKm: 'किमी सीमा कॉरिडोर के भीतर (0–{len} किमी) और से ≤ तक होनी चाहिए।',
    errSpeed: 'गति खंडीय गति {mps} किमी/घं से कम होनी चाहिए।',
    errReason: 'कारण आवश्यक है।',
    errWork: 'संबंधित कार्य चुनें।',
    confirm: 'पुष्टि करें',
    cancel: 'रद्द करें',
    lineUp: 'UP लाइन',
    lineDn: 'DN लाइन',
    lineBoth: 'दोनों लाइनें',
    relaxTitle: 'शिथिलन अनुरोध · {id}',
    relaxBody: 'नियंत्रण को बताया जाता है कि यह हिस्सा अधिक गति ले सकता है।',
    relaxSpeed: 'प्रस्तावित गति (किमी/घं)',
    relaxNote: 'आधार (टैम्पिंग रन, समेकन, माप)',
    errRelax: 'प्रस्तावित गति {v} से अधिक और {mps} किमी/घं से कम होनी चाहिए।',
    relaxNoteText: '{v} किमी/घं तक शिथिल करें: {note}',
    withdrawTsrTitle: 'TSR वापस लें · {id}',
    withdrawOrderTitle: 'आदेश वापस लें · {id}',
    withdrawReason: 'वापस लेने का कारण',
    toastTsrInForce: 'TSR {a}–{b} पर {v} किमी/घं लागू',
    toastTsrProposed: 'TSR {a}–{b} पर {v} किमी/घं नियंत्रण को प्रस्तावित',
    toastInjected: 'संबंधित कार्य जोड़ा गया; योजना फिर से बन रही है',
    toastImposed: 'TSR {id} लागू',
    toastWithdrawn: 'TSR {id} वापस लिया गया',
    toastRelax: '{id} पर शिथिलन अनुरोधित',
    toastIssued: '{form} {serial} जारी',
    toastOrderWithdrawn: 'आदेश {serial} वापस लिया गया',
    toastReceived: 'T/351 {serial} प्राप्त दर्ज',
    toastReconnected: 'T/351 {serial} रीकनेक्ट दर्ज',
    toastPower: '{id}: {state}',
    notifyRelax: '{id} पर शिथिलन अनुरोधित',
    notifyImposed: 'TSR {id} लागू',
    notifyWithdrawn: 'TSR {id} वापस लिया गया',
    replanReason: 'आपात TSR {id}',
  },
} as const;

type Key = keyof typeof strings.en;

/* printed sheets are always black on white (FormSheet); borders follow the text colour */
const sheetTable: CSSProperties = { width: '100%', borderCollapse: 'collapse', fontSize: 11, margin: '10px 0' };
const sheetCell: CSSProperties = { border: '1px solid currentColor', padding: '5px 7px', textAlign: 'left', verticalAlign: 'top' };
const sheetRow: CSSProperties = { display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', fontSize: 12, marginBottom: 8 };
const signGrid: CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 24, marginTop: 28, fontSize: 11 };
const signLine: CSSProperties = { borderTop: '1px solid currentColor', paddingTop: 4 };

const roleOf = (p: PortalId): Role => (p === 'tms' || p === 'smms' || p === 'tdms' ? p : 'control');

export default function FormsPage({ tab }: FormsPageProps) {
  const snapshot = useAppStore((s) => s.snapshot);
  const portal = usePortal();
  if (!snapshot) return <PlanPending />;
  return <Forms key={`${portal}:${tab ?? ''}`} snapshot={snapshot} role={roleOf(portal)} routeTab={tab} />;
}

function Forms({ snapshot, role, routeTab }: { snapshot: Snapshot; role: Role; routeTab?: FormsPageProps['tab'] }) {
  const t = useT(strings);
  const drawer = useDrawerParams();

  const user = useAppStore((s) => s.user);
  const approvals = useAppStore((s) => s.approvals);
  const forms = useAppStore((s) => s.forms);
  const tsrs = useAppStore((s) => s.tsrs);
  const powerBlocks = useAppStore((s) => s.powerBlocks);
  const executionLog = useAppStore((s) => s.executionLog);
  const setFormStatus = useAppStore((s) => s.setFormStatus);
  const updateTsr = useAppStore((s) => s.updateTsr);
  const setPowerBlock = useAppStore((s) => s.setPowerBlock);
  const notify = useAppStore((s) => s.notify);
  const toast = useAppStore((s) => s.toast);

  const corridor = snapshot.corridor;
  const tabs = TABS[role];
  const [tab, setTab] = useState<TabId>(() => {
    const want: TabId | undefined = routeTab === 'disconnections' ? 't351' : routeTab === 'powerblocks' ? 'power' : routeTab === 'caution' ? 'caution' : undefined;
    return want && tabs.includes(want) ? want : tabs[0];
  });
  const [station, setStation] = useState('');
  const [picked, setPicked] = useState<Partial<Record<TabId, string>>>({});
  const [modal, setModal] = useState<{ kind: 'addTsr' } | { kind: 'relax'; tsr: ManualTsr } | { kind: 'withdrawTsr'; tsr: ManualTsr } | { kind: 'withdrawOrder'; order: CautionOrder } | null>(null);

  const day = clamp(drawer.day ?? 0, 0, snapshot.result.weekly.occupancy.length - 1);
  const dayIso = snapshot.result.weekly.occupancy[day]?.date ?? snapshot.planStart;

  const canCaution = can(user, 'issueCaution');
  const canIntake = can(user, 'intake');
  const canDeptAct = can(user, 'execute') || can(user, 'intake');
  const canReceive = canCaution || can(user, 'grant');

  /* ── derived forms ─────────────────────────────────────── */
  const blocks = useMemo(() => workingBlocks(snapshot, approvals), [snapshot, approvals]);
  const blockById = useMemo(() => new Map(blocks.map((b) => [b.id, b])), [blocks]);
  const orders = useMemo(() => cautionOrders(snapshot, blocks, tsrs, forms, day), [snapshot, blocks, tsrs, forms, day]);
  const atStation = (o: CautionOrder) => !station || o.sections.some((i) => corridor.blockSections[i]?.from === station || corridor.blockSections[i]?.to === station);
  const t409 = orders.filter((o) => o.formType === 'T/409' && atStation(o));
  const t409b = orders.filter((o) => o.formType === 'T/409B' && atStation(o));
  const notices = useMemo(() => disconnectionNoticesWeek(snapshot, blocks, forms), [snapshot, blocks, forms]);
  const register = useMemo(() => tsrs.filter((x) => x.corridorId === corridor.id).sort((a, b) => (a.status === 'WITHDRAWN' ? 1 : 0) - (b.status === 'WITHDRAWN' ? 1 : 0)), [tsrs, corridor.id]);
  const powerList = useMemo(() => blocks.filter((b) => b.status !== 'REFUSED' && (b.oheSections.length > 0 || b.kind === 'POWER' || b.kind === 'TRAFFIC + POWER')).sort((a, b) => a.day - b.day || a.start - b.start), [blocks]);
  const clearedBlocks = useMemo(() => new Set(executionLog.filter((r) => r.corridorId === corridor.id && r.status !== 'IN_PROGRESS').map((r) => r.blockId)), [executionLog, corridor.id]);

  /* ── selection per tab (first row when nothing picked) ─── */
  const pick = <T,>(list: T[], key: (x: T) => string): T | null => list.find((x) => key(x) === picked[tab]) ?? list[0] ?? null;
  const selTsr = tab === 'tsr' ? pick(register, (x) => x.id) : null;
  const selOrder = tab === 'caution' ? pick(t409, (x) => x.orderNo) : tab === 'cautionB' ? pick(t409b, (x) => x.orderNo) : tab === 'tsr' && selTsr ? orders.find((o) => o.manual?.id === selTsr.id) ?? null : null;
  const selNotice = tab === 't351' ? pick(notices, (x) => x.noticeNo) : null;
  const selPower = tab === 'power' ? pick(powerList, (x) => x.id) : null;
  const choose = (id: string) => setPicked({ ...picked, [tab]: id });

  /* ── actions ───────────────────────────────────────────── */
  const imposeTsr = (x: ManualTsr) => {
    updateTsr(x.id, { status: 'IN_FORCE' });
    notify({ portals: ['field', 'tms', 'control'], kind: 'CRITICAL', title: t('notifyImposed', { id: x.id }), body: `${kmRange(x.fromKm, x.toKm)} ${x.line} · ${x.kmph} km/h · ${x.reason}`, route: '/app/control/caution' });
    toast({ title: t('toastImposed', { id: x.id }), body: `${kmRange(x.fromKm, x.toKm)} · ${x.kmph} km/h`, tone: 'crit' });
  };
  const issueOrder = (o: CautionOrder) => {
    setFormStatus(o.orderNo, 'ISSUED', `${o.formType} · ${o.section}`);
    toast({ title: t('toastIssued', { form: o.formType, serial: o.orderNo }), tone: 'ok' });
  };
  const noticeStatus = (n: DisconnectionNotice, status: 'ISSUED' | 'RECEIVED' | 'RECONNECTED') => {
    setFormStatus(n.noticeNo, status, `T/351 · ${n.gear}`);
    toast({ title: status === 'ISSUED' ? t('toastIssued', { form: 'T/351', serial: n.noticeNo }) : status === 'RECEIVED' ? t('toastReceived', { serial: n.noticeNo }) : t('toastReconnected', { serial: n.noticeNo }), tone: 'ok' });
  };
  const powerStatus = (b: WorkingBlock, status: 'DEENERGISED' | 'ENERGISED') => {
    setPowerBlock(b.id, status);
    toast({ title: t('toastPower', { id: b.id, state: status === 'DEENERGISED' ? t('powerDeenergised') : t('powerEnergised') }), body: `${b.sectionText} · ${hhmm(b.start)}–${hhmm(b.end)}`, tone: status === 'DEENERGISED' ? 'warn' : 'ok' });
  };

  /* ── columns ───────────────────────────────────────────── */
  const blockBtn = (id: string | null) =>
    id ? (
      <button className="btn btn-sm btn-ghost" onClick={(e) => { e.stopPropagation(); drawer.open('block', id); }}>
        {t('openBlock')}
      </button>
    ) : null;

  const tsrCols: Column<ManualTsr>[] = [
    { key: 'id', header: t('colNo'), render: (x) => <span className="mono strong">{x.id}</span> },
    { key: 'section', header: t('colSection'), render: (x) => <span className="small">{kmRange(x.fromKm, x.toKm)} · {x.line}</span> },
    { key: 'speed', header: t('colSpeed'), render: (x) => <span className="num strong">{x.kmph} km/h</span> },
    {
      key: 'status',
      header: t('colStatus'),
      render: (x) => (
        <div className="row-wrap" style={{ gap: 4 }}>
          <StatusBadge status={x.status} />
          {x.relaxationRequested && x.status !== 'WITHDRAWN' && <Badge tone="info" title={x.relaxationRequested.note}>{t('relaxRequested')}</Badge>}
        </div>
      ),
    },
    { key: 'reason', header: t('colReason'), hideMobile: true, render: (x) => <span className="small truncate" style={{ display: 'inline-block', maxWidth: 220 }} title={x.reason}>{x.reason}</span> },
    { key: 'since', header: t('colSince'), hideMobile: true, render: (x) => <span className="small muted">{timeAgo(x.since)} → {x.until ?? t('untilCancelled')}</span> },
    { key: 'loss', header: t('colLoss'), num: true, hideMobile: true, render: (x) => (x.taskId && snapshot.tsrLossPerDay[x.taskId] !== undefined ? <span className="num">{num(snapshot.tsrLossPerDay[x.taskId])}</span> : <span className="muted">{t('none')}</span>) },
    {
      key: 'actions',
      header: t('colActions'),
      render: (x) => {
        const out: ReactNode[] = [];
        if (role === 'control' && x.status === 'PROPOSED') out.push(<button key="imp" className="btn btn-sm btn-primary" disabled={!canCaution} title={canCaution ? undefined : t('noCaution')} onClick={(e) => { e.stopPropagation(); imposeTsr(x); }}>{t('impose')}</button>);
        if (role === 'control' && x.status === 'IN_FORCE') {
          const ok = !!x.relaxationRequested || (!!x.blockId && clearedBlocks.has(x.blockId));
          out.push(<button key="wd" className="btn btn-sm" disabled={!canCaution || !ok} title={!canCaution ? t('noCaution') : ok ? undefined : t('withdrawNeeds')} onClick={(e) => { e.stopPropagation(); setModal({ kind: 'withdrawTsr', tsr: x }); }}>{t('withdraw')}</button>);
        }
        if (role === 'tms' && x.status === 'IN_FORCE' && !x.relaxationRequested) out.push(<button key="rx" className="btn btn-sm" disabled={!canIntake} title={canIntake ? undefined : t('noIntake')} onClick={(e) => { e.stopPropagation(); setModal({ kind: 'relax', tsr: x }); }}>{t('relax')}</button>);
        out.push(blockBtn(x.blockId ?? null));
        return <div className="row" style={{ gap: 6, justifyContent: 'flex-end' }}>{out}</div>;
      },
    },
  ];

  const orderCols: Column<CautionOrder>[] = [
    { key: 'no', header: t('colNo'), render: (o) => <span className="mono small strong">{o.orderNo}</span> },
    { key: 'section', header: t('colSection'), render: (o) => <div><div className="small strong">{o.section}</div><div className="tiny muted">{kmRange(o.startKm, o.endKm)} · {o.line}</div></div> },
    { key: 'speed', header: t('colSpeed'), render: (o) => <div><span className="num strong">{o.speedKmph} km/h</span><div className="tiny muted">{t('normalSpeed', { v: o.normalSpeedKmph })}</div></div> },
    { key: 'valid', header: t('colValid'), hideMobile: true, render: (o) => <span className="small mono">{o.validFrom} → {o.validTo}</span> },
    { key: 'reason', header: t('colReason'), hideMobile: true, render: (o) => <span className="small truncate" style={{ display: 'inline-block', maxWidth: 220 }} title={o.reason}>{o.reason}</span> },
    { key: 'status', header: t('colStatus'), render: (o) => <StatusBadge status={o.status} /> },
    {
      key: 'actions',
      header: t('colActions'),
      render: (o) => {
        const proposed = o.manual?.status === 'PROPOSED';
        return (
          <div className="row" style={{ gap: 6, justifyContent: 'flex-end' }}>
            {role === 'control' && o.status === 'DRAFT' && (
              <button className="btn btn-sm btn-primary" disabled={!canCaution || proposed} title={!canCaution ? t('noCaution') : proposed ? t('issueProposed') : undefined} onClick={(e) => { e.stopPropagation(); issueOrder(o); }}>
                {t('issue')}
              </button>
            )}
            {role === 'control' && o.status === 'ISSUED' && (
              <button className="btn btn-sm" disabled={!canCaution} title={canCaution ? undefined : t('noCaution')} onClick={(e) => { e.stopPropagation(); setModal({ kind: 'withdrawOrder', order: o }); }}>
                {t('withdraw')}
              </button>
            )}
            {blockBtn(o.liftingBlockId)}
          </div>
        );
      },
    },
  ];

  const noticeCols: Column<DisconnectionNotice>[] = [
    { key: 'no', header: t('colNo'), render: (n) => <span className="mono small strong">{n.noticeNo}</span> },
    { key: 'block', header: t('colBlock'), render: (n) => { const b = blockById.get(n.blockId); return <div><div className="small mono">{n.blockId}</div>{b && <div className="tiny muted">{dateLabel(b.date)} · {b.sectionText}</div>}</div>; } },
    { key: 'gear', header: t('colGear'), hideMobile: true, render: (n) => <span className="small">{n.gear}</span> },
    { key: 'time', header: t('colTime'), render: (n) => <span className="small mono">{n.disconnectionTime} → {n.reconnectionTime}</span> },
    { key: 'status', header: t('colStatus'), render: (n) => <StatusBadge status={n.status} /> },
    {
      key: 'actions',
      header: t('colActions'),
      render: (n) => (
        <div className="row" style={{ gap: 6, justifyContent: 'flex-end' }}>
          {role === 'smms' && n.status === 'DRAFT' && <button className="btn btn-sm btn-primary" disabled={!canDeptAct} title={canDeptAct ? undefined : t('noDeptCap')} onClick={(e) => { e.stopPropagation(); noticeStatus(n, 'ISSUED'); }}>{t('issue')}</button>}
          {role === 'control' && n.status === 'ISSUED' && <button className="btn btn-sm btn-primary" disabled={!canReceive} title={canReceive ? undefined : t('noCaution')} onClick={(e) => { e.stopPropagation(); noticeStatus(n, 'RECEIVED'); }}>{t('markReceived')}</button>}
          {role === 'smms' && (n.status === 'ISSUED' || n.status === 'RECEIVED') && <button className="btn btn-sm" disabled={!canDeptAct} title={canDeptAct ? undefined : t('noDeptCap')} onClick={(e) => { e.stopPropagation(); noticeStatus(n, 'RECONNECTED'); }}>{t('markReconnected')}</button>}
          {blockBtn(n.blockId)}
        </div>
      ),
    },
  ];

  const powerCols: Column<WorkingBlock>[] = [
    { key: 'block', header: t('colBlock'), render: (b) => <div><div className="small mono strong">{b.id}</div><div className="tiny muted">{dateLabel(b.date)} · {hhmm(b.start)}–{hhmm(b.end)}</div></div> },
    { key: 'section', header: t('colSection'), render: (b) => <span className="small">{b.sectionText} · {b.line}</span> },
    { key: 'ohe', header: t('colOhe'), hideMobile: true, render: (b) => <span className="small">{b.oheSections.length ? b.oheSections.map((s) => s.label).join(', ') : t('none')}</span> },
    {
      key: 'status',
      header: t('colStatus'),
      render: (b) => {
        const rec = powerBlocks[b.id];
        const st = rec?.status ?? 'PENDING';
        return (
          <div>
            <Badge tone={st === 'DEENERGISED' ? 'warn' : st === 'ENERGISED' ? 'ok' : 'gray'}>{st === 'DEENERGISED' ? t('powerDeenergised') : st === 'ENERGISED' ? t('powerEnergised') : t('powerPending')}</Badge>
            {rec && <div className="tiny muted">{t('recordedBy', { by: rec.by, when: timeAgo(rec.at) })}</div>}
          </div>
        );
      },
    },
    {
      key: 'actions',
      header: t('colActions'),
      render: (b) => {
        const st = powerBlocks[b.id]?.status ?? 'PENDING';
        return (
          <div className="row" style={{ gap: 6, justifyContent: 'flex-end' }}>
            {st !== 'DEENERGISED' && <button className="btn btn-sm btn-primary" disabled={!canDeptAct} title={canDeptAct ? undefined : t('noDeptCap')} onClick={(e) => { e.stopPropagation(); powerStatus(b, 'DEENERGISED'); }}>{t('deenergise')}</button>}
            {st === 'DEENERGISED' && <button className="btn btn-sm btn-ok" disabled={!canDeptAct} title={canDeptAct ? undefined : t('noDeptCap')} onClick={(e) => { e.stopPropagation(); powerStatus(b, 'ENERGISED'); }}>{t('energise')}</button>}
            {blockBtn(b.id)}
          </div>
        );
      },
    },
  ];

  /* ── stats ─────────────────────────────────────────────── */
  const inForce = register.filter((x) => x.status === 'IN_FORCE');
  const dayOrders = [...orders.filter((o) => o.formType === 'T/409'), ...orders.filter((o) => o.formType === 'T/409B')];
  const tiles: ReactNode[] = [];
  if (tabs.includes('tsr')) tiles.push(<StatTile key="tsr" icon={<ShieldAlert size={14} />} label={t('statTsr')} value={inForce.length} sub={t('statTsrSub', { p: register.filter((x) => x.status === 'PROPOSED').length, r: inForce.filter((x) => x.relaxationRequested).length })} />);
  if (tabs.includes('caution')) tiles.push(<StatTile key="ord" icon={<FileText size={14} />} label={t('statOrders', { date: dateLabel(dayIso) })} value={dayOrders.length} sub={t('statOrdersSub', { issued: dayOrders.filter((o) => o.status === 'ISSUED').length, draft: dayOrders.filter((o) => o.status === 'DRAFT').length })} />);
  if (tabs.includes('t351')) tiles.push(<StatTile key="t351" icon={<Wrench size={14} />} label={t('statT351')} value={notices.length} sub={t('statT351Sub', { open: notices.filter((n) => n.status !== 'RECEIVED' && n.status !== 'RECONNECTED').length })} />);
  if (tabs.includes('power')) tiles.push(<StatTile key="pw" icon={<Zap size={14} />} label={t('statPower')} value={powerList.length} sub={t('statPowerSub', { n: powerList.filter((b) => powerBlocks[b.id]?.status === 'DEENERGISED').length })} />);

  const tabLabel: Record<TabId, Key> = { tsr: 'tabTsr', caution: 'tabCaution', cautionB: 'tabCautionB', t351: 'tabT351', power: 'tabPower' };
  const tabCount: Record<TabId, number> = { tsr: register.length, caution: t409.length, cautionB: t409b.length, t351: notices.length, power: powerList.length };
  const lede = role === 'tms' ? t('ledeTms') : role === 'smms' ? t('ledeSmms') : role === 'tdms' ? t('ledeTdms') : t('ledeControl');
  const showDay = tab === 'caution' || tab === 'cautionB';

  let table: ReactNode = null;
  if (tab === 'tsr') table = <DataTable<ManualTsr> columns={tsrCols} rows={register} rowKey={(x) => x.id} onRowClick={(x) => choose(x.id)} selectedKey={selTsr?.id} empty={t('emptyTsr')} />;
  else if (tab === 'caution') table = <div data-tour="caution-orders"><DataTable<CautionOrder> columns={orderCols} rows={t409} rowKey={(o) => o.orderNo} onRowClick={(o) => choose(o.orderNo)} selectedKey={selOrder?.orderNo} empty={t('emptyCaution', { date: dateLabel(dayIso) })} /></div>;
  else if (tab === 'cautionB') table = <div data-tour="caution-orders"><DataTable<CautionOrder> columns={orderCols} rows={t409b} rowKey={(o) => o.orderNo} onRowClick={(o) => choose(o.orderNo)} selectedKey={selOrder?.orderNo} empty={t('emptyCautionB', { date: dateLabel(dayIso) })} /></div>;
  else if (tab === 't351') table = <DataTable<DisconnectionNotice> columns={noticeCols} rows={notices} rowKey={(n) => n.noticeNo} onRowClick={(n) => choose(n.noticeNo)} selectedKey={selNotice?.noticeNo} empty={t('emptyT351')} />;
  else table = <DataTable<WorkingBlock> columns={powerCols} rows={powerList} rowKey={(b) => b.id} onRowClick={(b) => choose(b.id)} selectedKey={selPower?.id} empty={t('emptyPower')} />;

  let sheet: ReactNode = null;
  if (selOrder) sheet = <CautionSheet order={selOrder} dayIso={dayIso} division={corridor.division} record={forms[selOrder.orderNo]} />;
  else if (selNotice) sheet = <NoticeSheet notice={selNotice} block={blockById.get(selNotice.blockId) ?? null} />;
  else if (selPower) sheet = <IsolationSheet block={selPower} record={powerBlocks[selPower.id]} towerWagons={selPower.machines.map((id) => snapshot.feeds.machines.find((m) => m.id === id)).filter((m) => m?.type === 'TOWER_WAGON').map((m) => m?.label ?? '')} />;

  return (
    <div className="stack-lg">
      <PageHeader
        title={t('title')}
        lede={lede}
        badges={<span className="tiny muted">{t('nomenclature')}</span>}
        actions={
          role === 'control' ? (
            <button className="btn btn-primary btn-sm" disabled={!canCaution} title={canCaution ? undefined : t('noCaution')} onClick={() => setModal({ kind: 'addTsr' })}>
              <PlusCircle size={14} /> {t('addTsr')}
            </button>
          ) : role === 'tms' ? (
            <button className="btn btn-primary btn-sm" disabled={!canIntake} title={canIntake ? undefined : t('noIntake')} onClick={() => setModal({ kind: 'addTsr' })}>
              <PlusCircle size={14} /> {t('proposeTsr')}
            </button>
          ) : undefined
        }
      />

      <div className="grid grid-auto">{tiles}</div>

      {tabs.length > 1 && <Tabs<TabId> tabs={tabs.map((id) => ({ id, label: t(tabLabel[id]), count: tabCount[id] }))} value={tab} onChange={setTab} />}

      <div className="grid grid-main-aside" style={{ alignItems: 'start' }}>
        <Card>
          <CardHead
            title={t(tabLabel[tab])}
            right={
              tab === 'tsr' ? (
                <SimLabel kind="localOnly" />
              ) : showDay ? (
                <SimLabel kind="seededFeed" system="TMS" />
              ) : tab === 'power' ? (
                <span className="tiny muted">{t('tpcNote')}</span>
              ) : undefined
            }
          />
          {showDay && (
            <CardBody tight>
              <div className="form-grid">
                <Field label={t('planDay')}>
                  <select className="select" value={day} onChange={(e) => drawer.set('day', Number(e.target.value) || null)}>
                    {snapshot.result.weekly.occupancy.map((o) => <option key={o.day} value={o.day}>{dateLabel(o.date)}</option>)}
                  </select>
                </Field>
                <Field label={t('station')}>
                  <select className="select" value={station} onChange={(e) => setStation(e.target.value)}>
                    <option value="">{t('allStations')}</option>
                    {corridor.stations.map((s) => <option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}
                  </select>
                </Field>
              </div>
            </CardBody>
          )}
          <CardBody flush>{table}</CardBody>
        </Card>

        <Card>
          <CardHead title={t('previewTitle')} right={sheet ? <PrintButton label={t('print')} targetId="forms-sheet" /> : undefined} />
          <CardBody>{sheet ?? <EmptyState title={t('previewEmpty')} />}</CardBody>
        </Card>
      </div>

      {modal?.kind === 'addTsr' && <TsrModal mode={role === 'control' ? 'add' : 'propose'} snapshot={snapshot} onClose={() => setModal(null)} />}
      {modal?.kind === 'relax' && <RelaxModal tsr={modal.tsr} mps={corridor.mpsKmph} onClose={() => setModal(null)} />}
      {modal?.kind === 'withdrawTsr' && (
        <ReasonModal
          title={t('withdrawTsrTitle', { id: modal.tsr.id })}
          onClose={() => setModal(null)}
          onConfirm={(reason) => {
            const x = modal.tsr;
            updateTsr(x.id, { status: 'WITHDRAWN' });
            notify({ portals: ['field', 'tms', 'control'], kind: 'OK', title: t('notifyWithdrawn', { id: x.id }), body: reason, route: '/app/control/caution' });
            toast({ title: t('toastWithdrawn', { id: x.id }), body: reason, tone: 'ok' });
            setModal(null);
          }}
        />
      )}
      {modal?.kind === 'withdrawOrder' && (
        <ReasonModal
          title={t('withdrawOrderTitle', { id: modal.order.orderNo })}
          onClose={() => setModal(null)}
          onConfirm={(reason) => {
            setFormStatus(modal.order.orderNo, 'WITHDRAWN', reason);
            toast({ title: t('toastOrderWithdrawn', { serial: modal.order.orderNo }), body: reason, tone: 'info' });
            setModal(null);
          }}
        />
      )}

      <BlockDrawer blockId={drawer.blockId} onClose={() => drawer.close('block')} />
      <TaskDrawer taskId={drawer.taskId} onClose={() => drawer.close('task')} />
    </div>
  );
}

/* ── Printable sheets ──────────────────────────────────────── */
function CautionSheet({ order, dayIso, division, record }: { order: CautionOrder; dayIso: string; division: string; record?: { status: string; by: string; at: string } }) {
  const t = useT(strings);
  return (
    <FormSheet id="forms-sheet" title={order.formTitle} formNo={order.orderNo}>
      <div style={sheetRow}>
        <span><b>{t('sheetDivision')}:</b> {division}</span>
        <span><b>{t('sheetDate')}:</b> {dateLong(dayIso)}</span>
      </div>
      <div style={{ fontSize: 12 }}><b>{t('sheetTo')}:</b> {t('sheetToCaution')}</div>
      <table style={sheetTable}>
        <thead>
          <tr>
            <th style={sheetCell}>{t('sheetBetween')}</th>
            <th style={sheetCell}>{t('sheetLine')}</th>
            <th style={sheetCell}>{t('sheetCautionSpeed')}</th>
            <th style={sheetCell}>{t('sheetNormal')}</th>
            <th style={sheetCell}>{t('sheetReason')}</th>
            <th style={sheetCell}>{t('sheetValid')}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={sheetCell}><b>{order.section}</b><br />{kmRange(order.startKm, order.endKm)}</td>
            <td style={sheetCell}>{lineLabel(order.line)}</td>
            <td style={sheetCell}><b>{order.speedKmph} km/h</b></td>
            <td style={sheetCell}>{order.normalSpeedKmph} km/h</td>
            <td style={sheetCell}>{order.reason}</td>
            <td style={sheetCell}>{order.validFrom} → {order.validTo}</td>
          </tr>
        </tbody>
      </table>
      {order.affectedTrains.length > 0 && (
        <div style={{ fontSize: 11 }}><b>{t('sheetTrains')}:</b> {order.affectedTrains.map((x) => x.trainNo).join(', ')}</div>
      )}
      <div style={{ ...sheetRow, marginTop: 10 }}>
        <span><b>{t('sheetIssuedBy')}:</b> {order.issuedBy}</span>
        <span><b>{t('sheetStatus')}:</b> {t(`fs_${order.status}` as Key)}{record ? ` · ${record.by} · ${timeAgo(record.at)}` : ''}</span>
      </div>
      <div style={signGrid}>
        <div style={signLine}>{t('sheetSm')}</div>
        <div style={signLine}>{t('sheetSc')}</div>
      </div>
    </FormSheet>
  );
}

function NoticeSheet({ notice, block }: { notice: DisconnectionNotice; block: WorkingBlock | null }) {
  const t = useT(strings);
  const section = notice.section || block?.sectionText || t('none');
  return (
    <FormSheet id="forms-sheet" title={notice.formTitle} formNo={notice.noticeNo}>
      <div style={sheetRow}>
        <span><b>{t('sheetBlock')}:</b> {notice.blockId}</span>
        <span><b>{t('sheetDate')}:</b> {block ? dateLong(block.date) : t('none')}</span>
      </div>
      <div style={{ fontSize: 12 }}><b>{t('sheetTo')}:</b> {t('sheetToNotice', { section })}</div>
      <table style={sheetTable}>
        <tbody>
          <tr><th style={sheetCell}>{t('sheetGear')}</th><td style={sheetCell}>{notice.gear} · {kmRange(notice.startKm, notice.endKm)}</td></tr>
          <tr><th style={sheetCell}>{t('sheetDisconnect')}</th><td style={sheetCell}>{notice.disconnectionTime}</td></tr>
          <tr><th style={sheetCell}>{t('sheetReconnect')}</th><td style={sheetCell}>{notice.reconnectionTime}</td></tr>
          <tr><th style={sheetCell}>{t('sheetSafety')}</th><td style={sheetCell}>{notice.safetyAssurance}</td></tr>
          <tr><th style={sheetCell}>{t('sheetIncharge')}</th><td style={sheetCell}>{block?.approval?.incharge ?? notice.inCharge}</td></tr>
          <tr><th style={sheetCell}>{t('sheetStatus')}</th><td style={sheetCell}>{t(`fs_${notice.status}` as Key)}</td></tr>
        </tbody>
      </table>
      <div style={signGrid}>
        <div style={signLine}>{t('sheetSse')}</div>
        <div style={signLine}>{t('sheetSm')}</div>
      </div>
    </FormSheet>
  );
}

function IsolationSheet({ block, record, towerWagons }: { block: WorkingBlock; record?: { status: string; by: string; at: string }; towerWagons: string[] }) {
  const t = useT(strings);
  const st = record?.status ?? 'PENDING';
  return (
    <FormSheet id="forms-sheet" title={t('sheetPowerTitle')} formNo={block.id}>
      <div style={sheetRow}>
        <span><b>{t('sheetDate')}:</b> {dateLong(block.date)}</span>
        <span><b>{t('sheetWindow')}:</b> {hhmm(block.start)}–{hhmm(block.end)}</span>
      </div>
      <div style={{ fontSize: 12 }}>{block.sectionText} · {lineLabel(block.line)} · {kmRange(block.startKm, block.endKm)}</div>
      <div style={{ fontSize: 12, marginTop: 10 }}><b>{t('sheetIsolation')}</b></div>
      <table style={sheetTable}>
        <thead>
          <tr>
            <th style={sheetCell}>{t('colOhe')}</th>
            <th style={sheetCell}>{t('sheetSp')}</th>
            <th style={sheetCell}>km</th>
          </tr>
        </thead>
        <tbody>
          {block.oheSections.map((s) => (
            <tr key={s.id}>
              <td style={sheetCell}>{s.label}</td>
              <td style={sheetCell}>{s.spFrom} → {s.spTo}</td>
              <td style={sheetCell}>{kmRange(s.startKm, s.endKm)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <table style={sheetTable}>
        <tbody>
          <tr><th style={sheetCell}>{t('sheetTpc')}</th><td style={sheetCell}>{st === 'DEENERGISED' ? t('powerDeenergised') : st === 'ENERGISED' ? t('powerEnergised') : t('powerPending')}{record ? ` · ${record.by} · ${timeAgo(record.at)}` : ''}</td></tr>
          <tr><th style={sheetCell}>{t('sheetTower')}</th><td style={sheetCell}>{towerWagons.length ? towerWagons.join(', ') : t('none')}</td></tr>
          <tr><th style={sheetCell}>{t('sheetIncharge')}</th><td style={sheetCell}>{block.approval?.incharge ?? t('none')}</td></tr>
        </tbody>
      </table>
      <div style={{ fontSize: 10 }}>{t('tpcNote')}</div>
      <div style={signGrid}>
        <div style={signLine}>{t('sheetTrd')}</div>
        <div style={signLine}>{t('sheetTpcSign')}</div>
      </div>
    </FormSheet>
  );
}

/* ── Modals ────────────────────────────────────────────────── */
function TsrModal({ mode, snapshot, onClose }: { mode: 'add' | 'propose'; snapshot: Snapshot; onClose: () => void }) {
  const t = useT(strings);
  const user = useAppStore((s) => s.user);
  const addTsr = useAppStore((s) => s.addTsr);
  const addIntakeTask = useAppStore((s) => s.addIntakeTask);
  const runPlan = useAppStore((s) => s.runPlan);
  const toast = useAppStore((s) => s.toast);
  const corridor = snapshot.corridor;

  const [line, setLine] = useState<Line>('UP');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [speed, setSpeed] = useState('');
  const [reason, setReason] = useState('');
  const [inject, setInject] = useState(false);
  const [workType, setWorkType] = useState('');

  const a = Number(from);
  const b = Number(to);
  const v = Number(speed);
  const kmErr = from.trim() === '' || to.trim() === '' || !Number.isFinite(a) || !Number.isFinite(b) || a < 0 || b > corridor.lengthKm || a > b;
  const speedErr = speed.trim() === '' || !Number.isFinite(v) || v <= 0 || v >= corridor.mpsKmph;
  const reasonErr = !reason.trim();
  const workErr = mode === 'add' && inject && !workType;
  const blocked = kmErr || speedErr || reasonErr || workErr;
  const touched = from !== '' || to !== '';

  const confirm = () => {
    const tsr = addTsr({ corridorId: corridor.id, line, fromKm: a, toKm: b, kmph: v, reason: reason.trim(), status: mode === 'add' ? 'IN_FORCE' : 'PROPOSED' });
    toast({ title: mode === 'add' ? t('toastTsrInForce', { a: a.toFixed(1), b: b.toFixed(1), v }) : t('toastTsrProposed', { a: a.toFixed(1), b: b.toFixed(1), v }), body: tsr.id, tone: mode === 'add' ? 'crit' : 'info' });
    if (mode === 'add' && inject && WT[workType]) {
      const wt = WT[workType];
      addIntakeTask({ spec: { sourceId: `TSR/${tsr.id}`, label: `${wt.label} — ${tsr.id}`, workType, line, startKm: a, endKm: b, tsrKmph: v, daysOverdue: 0, note: reason.trim() }, label: `${wt.label} · ${kmRange(a, b)} ${line}`, dept: wt.dept, submittedBy: user?.name ?? 'Control', role: user?.role ?? 'UNKNOWN', source: 'EMERGENCY-TSR' });
      void runPlan({ reason: t('replanReason', { id: tsr.id }) });
      toast({ title: t('toastInjected'), body: wt.label, tone: 'info' });
    }
    onClose();
  };

  return (
    <Modal
      open
      onClose={onClose}
      title={mode === 'add' ? t('tsrTitleAdd') : t('tsrTitlePropose')}
      width={560}
      footer={
        <div className="row" style={{ justifyContent: 'flex-end', width: '100%' }}>
          <button className="btn" onClick={onClose}>{t('cancel')}</button>
          <button className="btn btn-primary" disabled={blocked} onClick={confirm}>{t('confirm')}</button>
        </div>
      }
    >
      <div className="stack">
        <div className="small muted">{mode === 'add' ? t('tsrBodyAdd') : t('tsrBodyPropose')}</div>
        <div className="grid grid-3" style={{ gap: 10 }}>
          <Field label={t('fFrom')}>
            <input className="input" type="number" step={0.1} value={from} onChange={(e) => setFrom(e.target.value)} />
          </Field>
          <Field label={t('fTo')}>
            <input className="input" type="number" step={0.1} value={to} onChange={(e) => setTo(e.target.value)} />
          </Field>
          <Field label={t('fLine')}>
            <select className="select" value={line} onChange={(e) => setLine(e.target.value as Line)}>
              <option value="UP">{t('lineUp')}</option>
              <option value="DN">{t('lineDn')}</option>
              <option value="BOTH">{t('lineBoth')}</option>
            </select>
          </Field>
        </div>
        {kmErr && touched && <div className="small" style={{ color: 'var(--crit)' }}>{t('errKm', { len: corridor.lengthKm })}</div>}
        <Field label={t('fSpeed')} error={speedErr && speed !== '' ? t('errSpeed', { mps: corridor.mpsKmph }) : undefined}>
          <input className="input" type="number" min={1} max={corridor.mpsKmph - 1} step={5} value={speed} onChange={(e) => setSpeed(e.target.value)} />
        </Field>
        <Field label={t('fReason')} error={reasonErr && reason !== '' ? t('errReason') : undefined}>
          <input className="input" value={reason} onChange={(e) => setReason(e.target.value)} />
        </Field>
        {mode === 'add' && (
          <>
            <label className="check">
              <input type="checkbox" checked={inject} onChange={(e) => setInject(e.target.checked)} /> {t('fInject')}
            </label>
            {inject && (
              <Field label={t('fWork')} error={workErr ? t('errWork') : undefined}>
                <select className="select" value={workType} onChange={(e) => setWorkType(e.target.value)}>
                  <option value="">{t('fWorkPick')}</option>
                  {Object.entries(WT).map(([k, d]) => <option key={k} value={k}>{d.label} · {d.dept}</option>)}
                </select>
              </Field>
            )}
          </>
        )}
      </div>
    </Modal>
  );
}

function RelaxModal({ tsr, mps, onClose }: { tsr: ManualTsr; mps: number; onClose: () => void }) {
  const t = useT(strings);
  const user = useAppStore((s) => s.user);
  const updateTsr = useAppStore((s) => s.updateTsr);
  const notify = useAppStore((s) => s.notify);
  const toast = useAppStore((s) => s.toast);
  const [speed, setSpeed] = useState('');
  const [note, setNote] = useState('');
  const v = Number(speed);
  const bad = speed.trim() === '' || !Number.isFinite(v) || v <= tsr.kmph || v >= mps;
  return (
    <Modal
      open
      onClose={onClose}
      title={t('relaxTitle', { id: tsr.id })}
      footer={
        <div className="row" style={{ justifyContent: 'flex-end', width: '100%' }}>
          <button className="btn" onClick={onClose}>{t('cancel')}</button>
          <button
            className="btn btn-primary"
            disabled={bad}
            onClick={() => {
              const text = t('relaxNoteText', { v, note: note.trim() || '—' });
              updateTsr(tsr.id, { relaxationRequested: { by: user?.name ?? 'Unknown', at: new Date().toISOString(), note: text } });
              notify({ portals: ['control'], kind: 'ACTION', title: t('notifyRelax', { id: tsr.id }), body: text, route: '/app/control/caution' });
              toast({ title: t('toastRelax', { id: tsr.id }), body: text, tone: 'ok' });
              onClose();
            }}
          >
            {t('confirm')}
          </button>
        </div>
      }
    >
      <div className="stack">
        <div className="small muted">{t('relaxBody')}</div>
        <div className="small">{kmRange(tsr.fromKm, tsr.toKm)} · {tsr.line} · {tsr.kmph} km/h · {tsr.reason}</div>
        <Field label={t('relaxSpeed')} error={bad && speed !== '' ? t('errRelax', { v: tsr.kmph, mps }) : undefined}>
          <input className="input" type="number" min={tsr.kmph + 1} max={mps - 1} step={5} value={speed} onChange={(e) => setSpeed(e.target.value)} />
        </Field>
        <Field label={t('relaxNote')}>
          <textarea className="textarea" rows={3} value={note} onChange={(e) => setNote(e.target.value)} />
        </Field>
      </div>
    </Modal>
  );
}

function ReasonModal({ title, onClose, onConfirm }: { title: string; onClose: () => void; onConfirm: (reason: string) => void }) {
  const t = useT(strings);
  const [reason, setReason] = useState('');
  const empty = !reason.trim();
  return (
    <Modal
      open
      onClose={onClose}
      title={title}
      footer={
        <div className="row" style={{ justifyContent: 'flex-end', width: '100%' }}>
          <button className="btn" onClick={onClose}>{t('cancel')}</button>
          <button className="btn btn-danger" disabled={empty} title={empty ? t('errReason') : undefined} onClick={() => onConfirm(reason.trim())}>{t('withdraw')}</button>
        </div>
      }
    >
      <Field label={t('withdrawReason')} error={empty ? t('errReason') : undefined}>
        <textarea className="textarea" rows={3} value={reason} onChange={(e) => setReason(e.target.value)} />
      </Field>
    </Modal>
  );
}
