/**
 * Strings for the block requisition drawer (EN + HI). Railway terms stay in
 * Latin script in Hindi (block, TSR, JPO, T/351, COA, OHE).
 */
export const blockStrings = {
  en: {
    subtitle: 'Block requisition',
    coLocated: 'Co-located',
    premiumConflict: 'Premium conflict',
    overridden: 'Window changed by Control',
    kindTraffic: 'Traffic block',
    kindPower: 'Power block',
    kindTrafficPower: 'Traffic + power block',
    kindDisconnection: 'Disconnection',
    // key / value
    date: 'Date',
    window: 'Window',
    sections: 'Block sections',
    powerIsolation: 'Power isolation',
    elementarySections: 'Elementary sections',
    machines: 'Machines',
    gangs: 'Gangs',
    incharge: 'In-charge',
    inchargeNone: 'Not named yet',
    inchargePlaceholder: 'Name of the block in-charge',
    inchargeSaved: 'In-charge recorded',
    inchargeHint: 'Only Control or the planning cell can name the in-charge.',
    resources: 'Resource override',
    resourcesHint: 'Only Control can reassign a machine or gang on a granted block.',
    resourcesSaved: 'Resources reassigned',
    machineSelect: 'Machine',
    crewSelect: 'Gang',
    keepPlanned: 'Keep planned',
    assign: 'Assign',
    noMachine: 'No machine',
    noGang: 'No gang',
    override: 'override',
    // works
    works: 'Works bundled',
    work: 'Work',
    nested: 'disconnection nested in block',
    why: 'Why',
    // traffic
    traffic: 'Traffic impact',
    train: 'Train',
    cls: 'Class',
    handling: 'Handling',
    delay: 'Delay',
    slw: 'Speed restriction (SLW)',
    held: 'Held at station',
    regulated: 'Regulated',
    noTrains: 'Laid entirely inside a natural headway gap — no train is disturbed.',
    delaySentence: '{trains} train(s) regulated · weighted delay {weighted} min (raw {raw} min).',
    premiumSentence: '{n} premium path(s) conflict with this window.',
    // rules
    rules: 'Rule checks',
    ruleCeiling: 'JPO 6 h ceiling',
    ruleMin: 'Minimum length',
    ruleConcurrent: 'Simultaneous possessions',
    rulePerDay: 'Possessions per day',
    rulePremium: 'Premium paths protected',
    rulePass: 'Pass',
    ruleFail: 'Fail',
    ruleDetailCeiling: '{span} min of {max} min allowed',
    ruleDetailMin: '{span} min, minimum {min} min',
    ruleDetailConcurrent: '{n} overlapping, limit {max}',
    ruleDetailPerDay: '{n} on this day, limit {max}',
    ruleDetailPremium: '{n} premium conflict(s)',
    // forms
    forms: 'Forms & isolation status',
    t351: 'T/351 disconnection notices',
    noT351: 'No S&T work in this block — no T/351 needed.',
    powerStatus: 'OHE isolation record',
    powerPending: 'Isolation pending',
    powerDeenergised: 'De-energised — permit to work in force',
    powerEnergised: 'Re-energised',
    openForms: 'Open forms',
    openCaution: 'Open caution desk',
    // workflow
    workflow: 'Joint approval',
    officer: 'Officer',
    concurredBy: 'Concurred by {by}',
    pending: 'Pending',
    objection: 'Objection',
    concur: 'Concur',
    object: 'Object',
    concurNote: 'Note (optional)',
    concurNotePlaceholder: 'e.g. gang confirmed, machine at site',
    concurDone: 'Concurrence recorded for {dept}',
    objectReason: 'Reason for objection',
    objectDone: 'Objection recorded for {dept}',
    objGang: 'Gang unavailable',
    objMachine: 'Machine unavailable',
    objNotice: 'Notice too short',
    objPartner: 'Partner department not ready',
    objOther: 'Other',
    objDetail: 'Details',
    objDetailRequired: 'A reason is required to object.',
    cannotConcur: 'Only the {officer} of {dept} can concur.',
    alreadyConcurred: 'Concurrence already recorded.',
    grantCard: 'Control decision',
    grant: 'Grant',
    grantWithChange: 'Grant with change',
    refuse: 'Refuse',
    lockCoa: 'Lock into COA',
    grantDone: 'Block {id} granted',
    grantChangeDone: 'Block {id} granted with a changed window',
    refuseDone: 'Block {id} refused',
    lockDone: 'Block {id} locked into the COA',
    grantHintConcur: 'Waiting for concurrence from {depts}.',
    grantHintRole: 'Only Control can grant a possession.',
    grantHintStatus: 'This block is already {status}.',
    lockHintRole: 'Only the Chief Controller can lock a block into the COA.',
    lockHintStatus: 'Lock is possible once the block is granted.',
    t351Warning: 'T/351 not yet received for S&T work in this block',
    t351Confirm: 'Grant anyway — the T/351 will be confirmed before the gear is disconnected',
    refuseReason: 'Reason for refusal',
    refTraffic: 'Traffic — no path available',
    refFailure: 'Failure / incident on the section',
    refGang: 'Gang not ready',
    refT351: 'T/351 not received',
    refMachine: 'Machine not arrived',
    refOther: 'Other',
    refDetail: 'Details',
    refDetailRequired: 'Choose a reason to refuse.',
    grantedAt: 'Granted by {by} · {when}',
    lockedAt: 'Locked by {by} · {when}',
    refusedAt: 'Refused by {by} · {when} · {reason}',
    // grant with change
    shift: 'Shift window',
    shortenTo: 'Shorten to (min)',
    newWindow: 'New window',
    affected: 'Trains affected',
    weightedDelay: 'Weighted delay',
    violations: 'Rule violations',
    noViolations: 'No rule violations for this window.',
    infeasible: 'This window is not feasible — adjust the shift or length.',
    confirm: 'Confirm',
    // execution
    execution: 'Execution',
    noExecution: 'Not started — no possession record for this block.',
    actualStart: 'Actual start',
    actualEnd: 'Actual clear',
    itemsDone: 'Works completed',
    recordStart: 'Record start',
    recordClear: 'Record clear',
    startTime: 'Start time',
    clearTime: 'Clear time',
    overrunCause: 'Overrun cause (optional)',
    speedOnLifting: 'Speed on lifting (km/h, blank = full speed)',
    startDone: 'Possession start recorded for {id}',
    clearDone: 'Line clear recorded for {id}',
    executeHint: 'Only Control or the gang in-charge can record possession times.',
    executeHintStatus: 'Possession can be recorded once the block is granted.',
    // audit
    audit: 'Audit trail',
    // bdms
    bdms: 'BDMS demand payload',
    bdmsHint: 'What the API would POST to BDMS. Not submitted to CRIS.',
    copyJson: 'Copy JSON',
    copied: 'Payload copied to clipboard',
    copyFailed: 'Clipboard not available — select the text and copy.',
    printReq: 'Print requisition',
    requisition: 'Block requisition',
    print: 'Print',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    plannedBy: 'Planned by',
    reference: 'Reference',
    demandType: 'Demand type',
    corridor: 'Corridor',
    line: 'Line',
    duration: 'Duration',
    department: 'Department',
    status: 'Status',
    signature: 'Signature of the requisitioning officer',
    signatureControl: 'Section Controller',
    minutes: 'min',
    // workflow state (select.workflowState)
    stateLabel: 'Workflow state',
    st_DRAFT: 'draft — not sent',
    st_PROPOSED: 'awaiting concurrence',
    st_CONCURRED: 'concurred — ready to grant',
    st_GRANTED: 'granted',
    st_LOCKED: 'locked',
    st_REFUSED: 'refused',
    st_SUPERSEDED: 'changed by a re-plan',
    sendToControl: 'Send to Control',
    sendAgain: 'Send again',
    sentToast: 'Block {id} sent to Control; concurrence requested',
    sendHint: 'Only a draft or refused block can be sent.',
    sendNoCap: 'Only the block planning cell can send a block.',
    notSentHint: 'The planning cell has not sent this block yet — nothing to concur or grant.',
    onBehalf: 'Record on behalf',
    onBehalfNoteRequired: 'Concurrence on behalf of {dept} needs a note (phone / paper reference).',
    concurStateHint: 'Concurrence is open while the block awaits it — this block is {state}.',
    grantNeedsConcur: 'Grant needs every department to concur first.',
    // alternatives, confidence, deviations
    alternatives: 'Alternative windows',
    confidence: 'Block confidence',
    deviations: 'Execution deviations',
    extensions: 'Extension requests',
    messages: 'Site messages',
    acks: 'Loco pilot acknowledgements',
    lateNow: 'Past its planned end now',
  },
  hi: {
    subtitle: 'ब्लॉक माँग-पत्र',
    coLocated: 'सह-स्थित',
    premiumConflict: 'प्रीमियम टकराव',
    overridden: 'Control ने समय-खिड़की बदली',
    kindTraffic: 'ट्रैफ़िक ब्लॉक',
    kindPower: 'पावर ब्लॉक',
    kindTrafficPower: 'ट्रैफ़िक + पावर ब्लॉक',
    kindDisconnection: 'डिस्कनेक्शन',
    date: 'तिथि',
    window: 'समय-खिड़की',
    sections: 'ब्लॉक सेक्शन',
    powerIsolation: 'पावर आइसोलेशन',
    elementarySections: 'एलिमेंटरी सेक्शन',
    machines: 'मशीनें',
    gangs: 'गैंग',
    incharge: 'प्रभारी',
    inchargeNone: 'अभी नाम दर्ज नहीं',
    inchargePlaceholder: 'ब्लॉक प्रभारी का नाम',
    inchargeSaved: 'प्रभारी दर्ज',
    inchargeHint: 'केवल Control या योजना प्रकोष्ठ प्रभारी का नाम दर्ज कर सकते हैं।',
    resources: 'संसाधन बदलाव',
    resourcesHint: 'केवल Control प्रदान किए गए ब्लॉक पर मशीन या गैंग बदल सकता है।',
    resourcesSaved: 'संसाधन पुनः आवंटित',
    machineSelect: 'मशीन',
    crewSelect: 'गैंग',
    keepPlanned: 'योजना अनुसार रखें',
    assign: 'आवंटित करें',
    noMachine: 'कोई मशीन नहीं',
    noGang: 'कोई गैंग नहीं',
    override: 'बदला गया',
    works: 'सम्मिलित कार्य',
    work: 'कार्य',
    nested: 'ब्लॉक के भीतर डिस्कनेक्शन',
    why: 'क्यों',
    traffic: 'ट्रैफ़िक प्रभाव',
    train: 'ट्रेन',
    cls: 'श्रेणी',
    handling: 'व्यवहार',
    delay: 'विलंब',
    slw: 'गति प्रतिबंध (SLW)',
    held: 'स्टेशन पर रोकी',
    regulated: 'नियमित',
    noTrains: 'प्राकृतिक हेडवे अंतराल के भीतर रखा गया — कोई ट्रेन प्रभावित नहीं।',
    delaySentence: '{trains} ट्रेन नियमित · भारित विलंब {weighted} मिनट (कच्चा {raw} मिनट)।',
    premiumSentence: '{n} प्रीमियम पथ इस खिड़की से टकराते हैं।',
    rules: 'नियम जाँच',
    ruleCeiling: 'JPO 6 घं. सीमा',
    ruleMin: 'न्यूनतम अवधि',
    ruleConcurrent: 'एक साथ पज़ेशन',
    rulePerDay: 'प्रति दिन पज़ेशन',
    rulePremium: 'प्रीमियम पथ सुरक्षित',
    rulePass: 'पास',
    ruleFail: 'फेल',
    ruleDetailCeiling: '{span} मिनट, अनुमत {max} मिनट',
    ruleDetailMin: '{span} मिनट, न्यूनतम {min} मिनट',
    ruleDetailConcurrent: '{n} ओवरलैप, सीमा {max}',
    ruleDetailPerDay: 'इस दिन {n}, सीमा {max}',
    ruleDetailPremium: '{n} प्रीमियम टकराव',
    forms: 'फ़ॉर्म व आइसोलेशन स्थिति',
    t351: 'T/351 डिस्कनेक्शन सूचनाएँ',
    noT351: 'इस ब्लॉक में S&T कार्य नहीं — T/351 आवश्यक नहीं।',
    powerStatus: 'OHE आइसोलेशन रिकॉर्ड',
    powerPending: 'आइसोलेशन लंबित',
    powerDeenergised: 'डी-एनर्जाइज़्ड — कार्य अनुमति प्रभावी',
    powerEnergised: 'पुनः एनर्जाइज़्ड',
    openForms: 'फ़ॉर्म खोलें',
    openCaution: 'सतर्कता डेस्क खोलें',
    workflow: 'संयुक्त स्वीकृति',
    officer: 'अधिकारी',
    concurredBy: '{by} ने सहमति दी',
    pending: 'लंबित',
    objection: 'आपत्ति',
    concur: 'सहमति दें',
    object: 'आपत्ति करें',
    concurNote: 'टिप्पणी (वैकल्पिक)',
    concurNotePlaceholder: 'जैसे गैंग पुष्ट, मशीन साइट पर',
    concurDone: '{dept} की सहमति दर्ज',
    objectReason: 'आपत्ति का कारण',
    objectDone: '{dept} की आपत्ति दर्ज',
    objGang: 'गैंग उपलब्ध नहीं',
    objMachine: 'मशीन उपलब्ध नहीं',
    objNotice: 'नोटिस बहुत कम',
    objPartner: 'साझेदार विभाग तैयार नहीं',
    objOther: 'अन्य',
    objDetail: 'विवरण',
    objDetailRequired: 'आपत्ति के लिए कारण आवश्यक है।',
    cannotConcur: 'केवल {dept} के {officer} सहमति दे सकते हैं।',
    alreadyConcurred: 'सहमति पहले से दर्ज है।',
    grantCard: 'Control का निर्णय',
    grant: 'प्रदान करें',
    grantWithChange: 'बदलाव के साथ प्रदान',
    refuse: 'अस्वीकार',
    lockCoa: 'COA में लॉक करें',
    grantDone: 'ब्लॉक {id} प्रदान',
    grantChangeDone: 'ब्लॉक {id} बदली खिड़की के साथ प्रदान',
    refuseDone: 'ब्लॉक {id} अस्वीकृत',
    lockDone: 'ब्लॉक {id} COA में लॉक',
    grantHintConcur: '{depts} की सहमति प्रतीक्षित।',
    grantHintRole: 'केवल Control पज़ेशन प्रदान कर सकता है।',
    grantHintStatus: 'यह ब्लॉक पहले से {status} है।',
    lockHintRole: 'केवल मुख्य नियंत्रक ब्लॉक को COA में लॉक कर सकते हैं।',
    lockHintStatus: 'ब्लॉक प्रदान होने के बाद लॉक संभव है।',
    t351Warning: 'इस ब्लॉक के S&T कार्य के लिए T/351 अभी प्राप्त नहीं',
    t351Confirm: 'फिर भी प्रदान करें — गियर डिस्कनेक्ट से पहले T/351 की पुष्टि होगी',
    refuseReason: 'अस्वीकृति का कारण',
    refTraffic: 'ट्रैफ़िक — पथ उपलब्ध नहीं',
    refFailure: 'सेक्शन पर विफलता / घटना',
    refGang: 'गैंग तैयार नहीं',
    refT351: 'T/351 प्राप्त नहीं',
    refMachine: 'मशीन नहीं पहुँची',
    refOther: 'अन्य',
    refDetail: 'विवरण',
    refDetailRequired: 'अस्वीकार करने के लिए कारण चुनें।',
    grantedAt: '{by} द्वारा प्रदान · {when}',
    lockedAt: '{by} द्वारा लॉक · {when}',
    refusedAt: '{by} द्वारा अस्वीकृत · {when} · {reason}',
    shift: 'खिड़की खिसकाएँ',
    shortenTo: 'घटाकर (मिनट)',
    newWindow: 'नई खिड़की',
    affected: 'प्रभावित ट्रेनें',
    weightedDelay: 'भारित विलंब',
    violations: 'नियम उल्लंघन',
    noViolations: 'इस खिड़की के लिए कोई नियम उल्लंघन नहीं।',
    infeasible: 'यह खिड़की संभव नहीं — शिफ्ट या अवधि बदलें।',
    confirm: 'पुष्टि करें',
    execution: 'निष्पादन',
    noExecution: 'शुरू नहीं — इस ब्लॉक का पज़ेशन रिकॉर्ड नहीं।',
    actualStart: 'वास्तविक शुरुआत',
    actualEnd: 'वास्तविक क्लियर',
    itemsDone: 'पूर्ण कार्य',
    recordStart: 'शुरुआत दर्ज करें',
    recordClear: 'क्लियर दर्ज करें',
    startTime: 'शुरुआत समय',
    clearTime: 'क्लियर समय',
    overrunCause: 'ओवररन कारण (वैकल्पिक)',
    speedOnLifting: 'उठाने पर गति (km/h, खाली = पूर्ण गति)',
    startDone: '{id} की पज़ेशन शुरुआत दर्ज',
    clearDone: '{id} की लाइन क्लियर दर्ज',
    executeHint: 'केवल Control या गैंग प्रभारी पज़ेशन समय दर्ज कर सकते हैं।',
    executeHintStatus: 'ब्लॉक प्रदान होने के बाद पज़ेशन दर्ज हो सकता है।',
    audit: 'ऑडिट ट्रेल',
    bdms: 'BDMS माँग पेलोड',
    bdmsHint: 'जो API BDMS को POST करेगा। CRIS को प्रेषित नहीं।',
    copyJson: 'JSON कॉपी करें',
    copied: 'पेलोड क्लिपबोर्ड पर कॉपी',
    copyFailed: 'क्लिपबोर्ड उपलब्ध नहीं — टेक्स्ट चुनकर कॉपी करें।',
    printReq: 'माँग-पत्र प्रिंट करें',
    requisition: 'ब्लॉक माँग-पत्र',
    print: 'प्रिंट',
    close: 'बंद करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    plannedBy: 'योजनाकार',
    reference: 'संदर्भ',
    demandType: 'माँग प्रकार',
    corridor: 'कॉरिडोर',
    line: 'लाइन',
    duration: 'अवधि',
    department: 'विभाग',
    status: 'स्थिति',
    signature: 'माँगकर्ता अधिकारी के हस्ताक्षर',
    signatureControl: 'अनुभाग नियंत्रक',
    minutes: 'मिनट',
    stateLabel: 'वर्कफ़्लो स्थिति',
    st_DRAFT: 'ड्राफ़्ट — भेजा नहीं गया',
    st_PROPOSED: 'सहमति की प्रतीक्षा में',
    st_CONCURRED: 'सहमत — प्रदान हेतु तैयार',
    st_GRANTED: 'प्रदत्त',
    st_LOCKED: 'लॉक',
    st_REFUSED: 'अस्वीकृत',
    st_SUPERSEDED: 'पुनः योजना से बदला',
    sendToControl: 'Control को भेजें',
    sendAgain: 'फिर से भेजें',
    sentToast: 'ब्लॉक {id} Control को भेजा गया; सहमति माँगी गई',
    sendHint: 'केवल ड्राफ़्ट या अस्वीकृत ब्लॉक भेजा जा सकता है।',
    sendNoCap: 'ब्लॉक केवल ब्लॉक योजना प्रकोष्ठ भेज सकता है।',
    notSentHint: 'योजना प्रकोष्ठ ने यह ब्लॉक अभी नहीं भेजा — सहमति या प्रदान के लिए कुछ नहीं।',
    onBehalf: 'की ओर से दर्ज करें',
    onBehalfNoteRequired: '{dept} की ओर से सहमति के लिए टिप्पणी (फ़ोन / पत्र संदर्भ) आवश्यक है।',
    concurStateHint: 'सहमति तभी खुली है जब ब्लॉक उसकी प्रतीक्षा में हो — यह ब्लॉक {state} है।',
    grantNeedsConcur: 'प्रदान से पहले सभी विभागों की सहमति चाहिए।',
    alternatives: 'वैकल्पिक समय-खिड़कियाँ',
    confidence: 'ब्लॉक विश्वसनीयता',
    deviations: 'निष्पादन विचलन',
    extensions: 'विस्तार अनुरोध',
    messages: 'साइट संदेश',
    acks: 'लोको पायलट पावती',
    lateNow: 'अभी नियोजित समाप्ति से आगे',
  },
} as const;

export type BlockKey = keyof typeof blockStrings.en;
