/**
 * Kit extras: honesty labels with the fixed wording, seed stamp, audit trail,
 * timeline, time scrubber, chip group, slider, print sheet, photo capture,
 * location picker.
 */
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Camera, Crosshair, FlaskConical, Info, Pause, Play, Printer, ShieldCheck, Trash2 } from 'lucide-react';
import { set as idbSet, get as idbGet, del as idbDel } from 'idb-keyval';
import type { Corridor, Line } from '../../engine/types';
import { snapToCorridor, type Snapped } from '../../engine/select';
import type { AuditEntry } from '../../store/useAppStore';
import { hhmm, timeAgo } from '../../lib/format';

/* ── Honesty labels (fixed wording, see docs/v4-spec.md §8) ─── */
export type SimKind = 'seededFeed' | 'seededRecords' | 'wttPositions' | 'simClock' | 'baseline' | 'model' | 'solver' | 'assumption' | 'planningEstimate' | 'localAuth' | 'localOnly' | 'notOfficial';

const SIM_TEXT: Record<SimKind, { label: string; text: (system?: string, seed?: number | string, source?: string) => string }> = {
  seededFeed: { label: 'Simulated feed', text: (sys, seed) => `Simulated feed — seeded ${sys ?? 'source'}-shaped data${seed !== undefined ? `, seed ${seed}` : ''}. No live link.` },
  seededRecords: { label: 'Seeded history', text: () => 'Records before today are seeded history; records made on this device are real app state.' },
  wttPositions: { label: 'Derived from timetable', text: () => 'Train positions derived from the working timetable, not GPS or NTES.' },
  simClock: { label: 'Simulated clock', text: () => 'Simulated clock (scrubber), not wall time.' },
  baseline: { label: 'Simulated baseline', text: () => 'Baseline: simulated decentralised FIFO practice, same seed, computed like-for-like.' },
  model: { label: 'Fitted model', text: () => 'Model fitted on seeded history; metrics on a held-out split.' },
  solver: { label: 'In-browser solver', text: () => 'In-browser solver: greedy construction + simulated annealing. CP-SAT reference formulation documented, not executed.' },
  assumption: { label: 'Assumption', text: (_s, _seed, source) => `Assumption — editable. Source: ${source ?? 'planning cell estimate'}.` },
  planningEstimate: { label: 'Planning estimate', text: () => 'Planning estimate from the block programme, not live running.' },
  localAuth: { label: 'Browser-local accounts', text: () => 'Browser-local demo accounts — no server, no real authentication.' },
  localOnly: { label: 'Stored on this device', text: () => 'Stored in this browser only — nothing is transmitted.' },
  notOfficial: { label: 'Not an official document', text: () => 'Generated by SAMANVAY — not an official document until signed.' },
};

export function SimLabel({ kind, system, seed, source, short }: { kind: SimKind; system?: string; seed?: number | string; source?: string; short?: boolean }) {
  const t = SIM_TEXT[kind];
  const cls = kind === 'assumption' ? 'tag-assumption' : 'tag-sim';
  return (
    <span className={cls} title={t.text(system, seed, source)}>
      {kind === 'assumption' ? <ShieldCheck size={10} /> : <FlaskConical size={10} />}
      {short ? t.label.split(' ')[0] : t.label}
    </span>
  );
}

export function SourceLabel({ text = 'Target / literature (SIH 2026 deck)' }: { text?: string }) {
  return (
    <span className="tag-assumption" title={text} style={{ borderStyle: 'dotted' }}>
      <Info size={10} />
      Target / literature
    </span>
  );
}

export function SeedStamp({ seed, runId, iterations, ms }: { seed: number | string; runId?: number | string; iterations?: number; ms?: number }) {
  return (
    <span className="tiny muted mono" title="Every number on this page comes from this engine run">
      seed {seed}{runId !== undefined ? ` · run ${runId}` : ''}{iterations ? ` · ${iterations.toLocaleString('en-IN')} iterations` : ''}{ms !== undefined ? ` · ${(ms / 1000).toFixed(1)} s` : ''}
    </span>
  );
}

/* ── Audit trail / timeline ─────────────────────────────────── */
export function AuditTrail({ entries, limit = 12 }: { entries: AuditEntry[]; limit?: number }) {
  if (!entries.length) return <div className="empty">No actions recorded yet.</div>;
  return (
    <ul className="timeline">
      {entries.slice(0, limit).map((e) => (
        <li key={e.id} className={e.action.includes('REFUSED') || e.action.includes('OBJECTION') ? 'crit' : e.action.includes('GRANTED') || e.action.includes('CONCUR') || e.action.includes('CLEARED') ? 'ok' : ''}>
          <div className="row" style={{ gap: 6 }}>
            <b className="small">{e.action.replace(/_/g, ' ').toLowerCase().replace(/^\w/, (c) => c.toUpperCase())}</b>
            <span className="when right">{timeAgo(e.at)}</span>
          </div>
          <div className="tiny muted">
            {e.by} · {e.role.replace(/_/g, ' ').toLowerCase()}
            {e.detail ? ` · ${e.detail}` : ''}
          </div>
        </li>
      ))}
    </ul>
  );
}

export function Timeline({ steps }: { steps: { label: ReactNode; when?: string; state: 'done' | 'current' | 'pending'; note?: ReactNode }[] }) {
  return (
    <ul className="timeline">
      {steps.map((s, i) => (
        <li key={i} className={s.state === 'done' ? 'ok' : s.state === 'current' ? 'warn' : ''} style={{ opacity: s.state === 'pending' ? 0.6 : 1 }}>
          <div className="row" style={{ gap: 6 }}>
            <b className="small">{s.label}</b>
            {s.when && <span className="when right">{s.when}</span>}
          </div>
          {s.note && <div className="tiny muted">{s.note}</div>}
        </li>
      ))}
    </ul>
  );
}

/* ── Time scrubber (simulated clock) ────────────────────────── */
export function TimeScrubber({ minute, onChange, playing, onPlay, speed = 60, dayLabel, onNow }: { minute: number; onChange: (m: number) => void; playing: boolean; onPlay: (p: boolean) => void; speed?: number; dayLabel?: string; onNow?: () => void }) {
  useEffect(() => {
    if (!playing) return;
    const id = setInterval(() => onChange((minute + Math.max(1, Math.round(speed / 60))) % 1440), 1000);
    return () => clearInterval(id);
  }, [playing, minute, speed, onChange]);
  return (
    <div className="row" style={{ gap: 10, flexWrap: 'wrap' }} data-tour="time-scrubber">
      <button className="btn btn-sm btn-icon" onClick={() => onPlay(!playing)} aria-label={playing ? 'Pause' : 'Play'}>
        {playing ? <Pause /> : <Play />}
      </button>
      <span className="mono strong num" style={{ minWidth: 48 }}>{hhmm(minute)}</span>
      <input type="range" min={0} max={1439} value={minute} onChange={(e) => onChange(Number(e.target.value))} style={{ flex: 1, minWidth: 160 }} aria-label="Minute of day" />
      {dayLabel && <span className="small muted">{dayLabel}</span>}
      {onNow && (
        <button className="btn btn-sm" onClick={onNow}>Now</button>
      )}
      <SimLabel kind="simClock" short />
    </div>
  );
}

/* ── Chip group / slider ────────────────────────────────────── */
export function ChipGroup<T extends string>({ options, value, onChange, multi }: { options: { value: T; label: ReactNode; icon?: ReactNode }[]; value: T | T[]; onChange: (v: T | T[]) => void; multi?: boolean }) {
  const selected = Array.isArray(value) ? value : [value];
  return (
    <div className="row-wrap" role="group">
      {options.map((o) => {
        const on = selected.includes(o.value);
        return (
          <button
            key={o.value}
            type="button"
            className={`btn btn-sm ${on ? 'btn-dark' : ''}`}
            aria-pressed={on}
            onClick={() => {
              if (!multi) return onChange(o.value);
              onChange(on ? (selected.filter((v) => v !== o.value) as T[]) : ([...selected, o.value] as T[]));
            }}
          >
            {o.icon}
            {o.label}
          </button>
        );
      })}
    </div>
  );
}

export function Slider({ label, value, min, max, step = 1, onChange, format, hint }: { label: ReactNode; value: number; min: number; max: number; step?: number; onChange: (v: number) => void; format?: (v: number) => string; hint?: ReactNode }) {
  return (
    <div className="field">
      <div className="row">
        <label className="grow">{label}</label>
        <span className="mono strong num">{format ? format(value) : value}</span>
      </div>
      <input type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} />
      {hint && <div className="hint">{hint}</div>}
    </div>
  );
}

/* ── Printable form sheet ───────────────────────────────────── */
export function PrintButton({ label = 'Print', targetId }: { label?: string; targetId?: string }) {
  const onPrint = () => {
    if (targetId) document.body.setAttribute('data-print-only', targetId);
    window.print();
    setTimeout(() => document.body.removeAttribute('data-print-only'), 500);
  };
  return (
    <button className="btn btn-sm" onClick={onPrint}>
      <Printer /> {label}
    </button>
  );
}

export function FormSheet({ id, title, formNo, children, watermark = true }: { id?: string; title: ReactNode; formNo?: string; children: ReactNode; watermark?: boolean }) {
  return (
    <div id={id} className="form-sheet card" style={{ position: 'relative', padding: 24, background: '#fff', color: '#111' }} data-print-target={id}>
      {watermark && (
        <div className="tiny" style={{ position: 'absolute', top: 10, right: 12, color: '#8a8a8a', border: '1px dashed #bbb', padding: '2px 6px', borderRadius: 4 }}>
          Generated by SAMANVAY — not an official document until signed
        </div>
      )}
      <div style={{ borderBottom: '2px solid #111', paddingBottom: 8, marginBottom: 12 }}>
        <div className="caps" style={{ color: '#444' }}>Indian Railways · Government of India</div>
        <h3 style={{ color: '#111' }}>{title}</h3>
        {formNo && <div className="mono small" style={{ color: '#333' }}>{formNo}</div>}
      </div>
      {children}
    </div>
  );
}

/* ── Photo capture (compressed, stored in IndexedDB) ────────── */
async function compressImage(file: File, maxPx = 1280, quality = 0.7): Promise<{ full: Blob; thumb: string }> {
  const bitmap = await createImageBitmap(file);
  const scale = Math.min(1, maxPx / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement('canvas');
  canvas.width = Math.round(bitmap.width * scale);
  canvas.height = Math.round(bitmap.height * scale);
  const ctx = canvas.getContext('2d')!;
  ctx.drawImage(bitmap, 0, 0, canvas.width, canvas.height);
  const full: Blob = await new Promise((res) => canvas.toBlob((b) => res(b!), 'image/jpeg', quality));
  const tScale = Math.min(1, 240 / Math.max(canvas.width, canvas.height));
  const tc = document.createElement('canvas');
  tc.width = Math.round(canvas.width * tScale);
  tc.height = Math.round(canvas.height * tScale);
  tc.getContext('2d')!.drawImage(canvas, 0, 0, tc.width, tc.height);
  return { full, thumb: tc.toDataURL('image/jpeg', 0.6) };
}

export async function loadPhoto(photoId: string): Promise<string | null> {
  const blob = await idbGet<Blob>(`photo:${photoId}`);
  return blob ? URL.createObjectURL(blob) : null;
}

export async function deletePhoto(photoId: string) {
  await idbDel(`photo:${photoId}`);
}

export function PhotoCapture({ value, onChange, label = 'Take or choose a photo' }: { value: { photoId: string; thumb: string } | null; onChange: (v: { photoId: string; thumb: string } | null) => void; label?: string }) {
  const ref = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  const pick = async (file: File | undefined) => {
    if (!file) return;
    setBusy(true);
    try {
      const { full, thumb } = await compressImage(file);
      const photoId = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
      await idbSet(`photo:${photoId}`, full);
      onChange({ photoId, thumb });
    } finally {
      setBusy(false);
    }
  };
  return (
    <div className="stack">
      <input ref={ref} type="file" accept="image/*" capture="environment" hidden onChange={(e) => void pick(e.target.files?.[0])} />
      {value ? (
        <div className="row" style={{ alignItems: 'flex-start' }}>
          <img src={value.thumb} alt="Captured" style={{ width: 120, height: 120, objectFit: 'cover', borderRadius: 8, border: '1px solid var(--line)' }} />
          <div className="stack">
            <button type="button" className="btn btn-sm" onClick={() => ref.current?.click()}>
              <Camera /> Retake
            </button>
            <button type="button" className="btn btn-sm btn-ghost" onClick={() => { void deletePhoto(value.photoId); onChange(null); }}>
              <Trash2 /> Remove
            </button>
          </div>
        </div>
      ) : (
        <button type="button" className="btn btn-lg" style={{ borderStyle: 'dashed', minHeight: 96, justifyContent: 'center' }} onClick={() => ref.current?.click()} disabled={busy}>
          <Camera /> {busy ? 'Compressing…' : label}
        </button>
      )}
      <div className="tiny muted">Photos are compressed to 1280 px and stored on this device only.</div>
    </div>
  );
}

/* ── Location picker (GPS → nearest chainage) ───────────────── */
export interface LocationValue {
  lat?: number;
  lng?: number;
  accuracyM?: number;
  km?: number;
  line?: Line;
  station?: string;
  sectionLabel?: string;
  distanceM?: number;
}

export function LocationPicker({ corridor, value, onChange, labels }: { corridor: Corridor; value: LocationValue; onChange: (v: LocationValue) => void; labels?: { use: string; locating: string; found: string; denied: string; station: string; km: string } }) {
  const L = labels ?? { use: 'Use my location', locating: 'Finding your location…', found: 'Location captured', denied: 'Location not available — pick the nearest station below.', station: 'Nearest station', km: 'Chainage (km)' };
  const [state, setState] = useState<'idle' | 'locating' | 'ok' | 'denied'>(value.lat ? 'ok' : 'idle');
  const locate = () => {
    if (!navigator.geolocation) return setState('denied');
    setState('locating');
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        const s: Snapped = snapToCorridor(corridor, pos.coords.latitude, pos.coords.longitude);
        onChange({ ...value, lat: pos.coords.latitude, lng: pos.coords.longitude, accuracyM: Math.round(pos.coords.accuracy), km: s.km, station: s.station, sectionLabel: s.sectionLabel, distanceM: s.distanceM });
        setState('ok');
      },
      () => setState('denied'),
      { enableHighAccuracy: true, timeout: 12000, maximumAge: 30000 }
    );
  };
  const setStation = (code: string) => {
    const st = corridor.stations.find((s) => s.code === code);
    if (!st) return;
    onChange({ ...value, station: st.code, km: st.km, sectionLabel: undefined, lat: st.lat, lng: st.lng, distanceM: undefined });
  };
  return (
    <div className="stack">
      <div className="row-wrap">
        <button type="button" className="btn" onClick={locate} disabled={state === 'locating'}>
          <Crosshair className={state === 'locating' ? 'spin' : ''} /> {state === 'locating' ? L.locating : L.use}
        </button>
        {state === 'ok' && value.km !== undefined && (
          <span className="badge badge-ok">
            {L.found} · km {value.km.toFixed(1)} · {value.station}
            {value.distanceM !== undefined ? ` · ${value.distanceM >= 1000 ? `${(value.distanceM / 1000).toFixed(1)} km` : `${value.distanceM} m`} from line` : ''}
            {value.accuracyM ? ` · ±${value.accuracyM} m` : ''}
          </span>
        )}
        {state === 'denied' && <span className="badge badge-warn">{L.denied}</span>}
      </div>
      <div className="form-grid">
        <div className="field">
          <label>{L.station}</label>
          <select className="select" value={value.station ?? ''} onChange={(e) => setStation(e.target.value)}>
            <option value="">—</option>
            {corridor.stations.map((s) => (
              <option key={s.code} value={s.code}>{s.code} · {s.name} (km {s.km})</option>
            ))}
          </select>
        </div>
        <div className="field">
          <label>{L.km}</label>
          <input className="input" type="number" min={0} max={corridor.lengthKm} step={0.1} value={value.km ?? ''} onChange={(e) => onChange({ ...value, km: e.target.value === '' ? undefined : Number(e.target.value) })} />
        </div>
      </div>
    </div>
  );
}
